### ISSUE TITLE
lodash instead of underscore maybe?

### ISSUE THREAD

**Issue by tomByrer** [atom/underscore-plus#13]
Lots of [new changes lately](https://github.com/lodash/lodash/releases) that makes lodash even faster than underscore, while staying compatible.  jdalton is good about keeping on top of bugs, tests, & improvements (partly thanks to Dojo Foundation funding).  Also lodash has some of the string manipulation you added built-in.

**Comment by jdalton** [comment]
> jdalton is good about keeping on top of bugs, tests, & improvements (partly thanks to Dojo Foundation funding).

I got pinged here so just wanted to pop in and clear up that comment. The Dojo Foundation doesn't pay me. It's a foundation that provides [the CLA](http://dojofoundation.org/about/cla) and holds the copyright. I work on lodash on my own time and am not sponsored by anyone.

**Comment by kevinsawicki** [comment]
@tomByrer Thanks for bringing this up but I don't think this library is likely to change "backends" given it has little to no future.

This library was originally extracted out of Atom's core source to allow packages that were also being extracted to depend on explicit versions.

In hindsight, more thought should have been given into extracting multiple libraries for the different helpers that grew organically over time so that underscore wasn't a requirement just to use a helper like `deepClone`.

So going forward, my preference would be to just extract the bits from this library into cohesive other libraries for key path helpers, object helpers, view helpers, etc.
