### ISSUE TITLE
| (pipe) looks too much like I (capital i)

### ISSUE THREAD

**Issue by shunfu** [atom/underscore-plus#17]
This pkg helps humanize keystrokes with shift, but I think it's more confusing when shift+\ is combined into |.

Case in point, I was recently confused by a package with the humanized keybinding ⌘|. I was trying to do ⌘I the whole time and couldn't figure out why it didn't work. I changed the keymaps json file to be `cmd-shift-\\`, and thus expected the context menu to show the more clear ⌘⇧\, but it remained the confusing ⌘|.

https://github.com/atom/underscore-plus/blob/master/src/underscore-plus.coffee#L33

**Comment by Arcanemagus** [comment]
Unfortunately the font choices Apple has used on their keyboard design is out of the scope of this project. 😉

As for how it looks inside Atom, you can pick a different theme or customize the font used by Atom if you find it confusing there. Note that if the keybind is _not_ humanized, it shows the <kbd>Shift</kbd> key:
`ctrl-|` / <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>\\</kbd>:
![image](https://user-images.githubusercontent.com/427137/38106371-9f8fd37e-3343-11e8-9c12-a17bcb31c00e.png)

`ctrl-shift-I` / <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>i</kbd> :
![image](https://user-images.githubusercontent.com/427137/38106395-b4255638-3343-11e8-9ca6-24f416315bdf.png)

Thanks for reaching out!

Because we treat our issues list as [the Atom team's backlog](https://en.wikipedia.org/wiki/Scrum_(software_development)#Product_backlog), we close issues that are questions since [they don't represent a task needing to be completed](http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html). For most questions about Atom there are a lot of options, check out:

* [The Atom Flight Manual](http://flight-manual.atom.io)
* [The Atom FAQ on Discuss](https://discuss.atom.io/c/faq)
* [Discuss, the official Atom and Electron message board](https://discuss.atom.io)
* [Join the Atom Slack team](http://atom-slack.herokuapp.com/)

On Discuss and in the Atom Slack team, there are a bunch of helpful community members that should be willing to point you in the right direction.

**Comment by Arcanemagus** [comment]
> How is the similar appearance of `|`, `l` and `I` mac specific

Because that's specific to Apple's keyboard? They aren't similar on mine. Since it looks like the `one-dark` theme uses a sans-serif font for that within Atom it might be worth filing an issue over there to see if making it so `I` shows with serifs is something worth looking into.

> FWIW I agree that in general `shift+\` is more clear than `|`.

If you are talking about the entire "humanizing" of the keybinds that's an entirely different issue that spreads across Atom's entire keybinding handling as it is done everywhere.

**Comment by cs01** [comment]
> If you are talking about the entire "humanizing" of the keybinds that's an entirely different issue that spreads across Atom's entire keybinding handling as it is done everywhere.

Yes we are talking about humanizing the keybindings everywhere. It's difficult to distinguish between some sans-serif characters. I believe that is what Sam what getting at initially:

> This pkg helps humanize keystrokes with shift, but I think it's more confusing when shift+\ is combined into |.
